usgs/earthquake-design-ws

test/design-handler-test.spec.js

fixes usgs/earthquake-design-ws#10
- Fixed test.

added expect for test and added a restore that was missing

---

src/handler/design-handler.js
src/lib/design-factory.js
src/lib/site-amplification-factory.js
src/lib/web-service.js
test/design-factory.spec.js

Puts several of the pieces together. Still some more work to do, but this demonstrates a working tool.

Integration

---

src/lib/design-category-factory.js
src/lib/site-amplification-factory.js
test/design-category-factory.spec.js

design-category-factory

---

src/lib/web-service.js
test/web-service.spec.js

This is not complete coverage, but it is a start.

Add tests for web-service

---

.travis.yml
etc/cities34.js
package.json
src/lib/design-factory.js
src/lib/legacy-factory.js
test/cities34.spec.js
test/design-factory.spec.js
test/legacy-factory.spec.js

Adding QA test. Fixed some bugs it revealed.
fixes #53 
fixes #54 
fixes #56

Cities 34 QA

---

configurer/questions.js
package.json
src/htdocs/deterministic.html
src/htdocs/index.html
src/lib/deterministic-factory.js
src/lib/deterministic-handler.js
src/lib/web-service.js
test/asce7_16-qc.spec.js
test/web-service.spec.js

fixes #83 
fixes #84 
fixes #85 
fixes #86 
relates to #81

Deterministic

---

src/lib/ground-motion-factory.js
test/ground-motion-factory.spec.js

Spatially Interpolate Ground Motion

---

src/lib/ground-motion-factory.js
src/lib/util/number-utils.js
test/ground-motion-factory.spec.js

Update GroundMotionFactory to use NumberUtils for spatial interpolation

---

src/lib/risk-coefficient-factory.js
src/lib/risk-coefficient-handler.js
test/probabilistic-factory.spec.js
test/risk-coefficient-factory.spec.js
test/risk-coefficient-handler.spec.js

fixes #100 
This includes #82, you can merge that PR first or merge this PR and close the other issue.

RiskTargetingCoefficientFactory

---

src/lib/risk-targeting-coefficient-handler.js
src/lib/web-service.js
test/risk-targeting-coefficient-handler.spec.js

I think this is all that's required, the rest is handled by the handler.
requires https://github.com/usgs/earthquake-design-ws/pull/103 (merge first)
fixes #99

Add risk-coefficient endpoint

---

src/htdocs/index.html
src/htdocs/risk-coefficient.html

Risk Targeting Coefficient Documentation

---

src/htdocs/risk-coefficient.html

Update Risk Coefficient Endpoint documentation per Nico's input

---

src/lib/metadata-factory.js
test/metadata-factory.spec.js

Fixes #111 
Not sure why Codecov thinks this is killing the coverage for the entire project?

MetadataFactory

---

.gitignore
docker-compose.yml
package.json
src/server.js
test/asce41_13-factory.spec.js
test/asce41_13-handler.spec.js
test/asce7_16-handler.spec.js
test/gridded-data-factory.spec.js
test/gridded-data-hander.spec.js
test/legacy/deterministic-hazard-factory.spec.js
test/legacy/legacy-factory.spec.js
test/legacy/metadata-factory.spec.js
test/legacy/probabilistic-hazard-factory.spec.js
test/legacy/risk-targeting-factory.spec.js
test/util/web-service-accessor.spec.js
test/web-service.spec.js

Updates to prepare for release
- Updated version number
- Update dependencies
- Updated configuration methodology

V0.3.0 RC1

---

src/lib/site-amplification-factory.js

added site amplification restrictions for each edition

---

src/lib/site-amplification-factory.js

fixes #145
test: http://localhost:8000/ws/designmaps/asce7-16.json?latitude=34&longitude=-118&riskCategory=III&siteClass=D%20(default)&title=Example

added s1 restrictions

---

.gitignore
configurer/questions.js
package.json
src/htdocs/css/index.css
src/htdocs/index.html
src/lib/util/config.js
src/lib/web-service.js
src/server.js

Pull request to baseline changes we made to get the Jenkins CICD project up-and-running.  Includes some project configuration refactoring.

Build vars

---

configurer/questions.js
src/lib/util/config.js
src/server.js

Remove commented code from https://github.com/usgs/earthquake-design-ws/pull/174

Remove commented code

---

README.md

Update README with database setup steps

---

src/lib/db/deterministic/documents.json
src/lib/db/deterministic/regions.json
src/lib/db/probabilistic/documents.json
src/lib/db/probabilistic/regions.json
src/lib/db/risk-coefficient/documents.json
src/lib/db/risk-coefficient/regions.json

fixes #164 
With the data loaded in, https://github.com/usgs/earthquake-design-ws/issues/163 we should be able to start testing the ASCE7-16 (non-legacy) endpoint.

Update with 2014 data

---

configurer/questions.js
src/htdocs/index.html
src/htdocs/t-sub-l.html
src/lib/t-sub-l-data-factory.js
src/lib/t-sub-l-data-handler.js
src/lib/web-service.js
test/t-sub-l-data-factory.spec.js
test/t-sub-l-data-handler.spec.js

This branch should most satisfy t-sub-l requirements specified in:
fixes #159 
fixes #160 
fixes #161 
See #158 Pull Request for loading the data.

T sub l service

---

package.json

Updated the code version in package.json from 0.3.2 to 0.4.0.

Sprint version bug (package.json)

---

src/lib/web-service.js

Using two spaces indentation for pretty printing.

---

src/lib/db/deterministic/documents.json
src/lib/db/probabilistic/documents.json
src/lib/db/risk-coefficient/documents.json

Update model number to v4.0.x for ASCE7-16

---

README.md

Add commands for loading component end point data to main README

---

src/htdocs/asce7-10.html
src/htdocs/index.html

Fixes Issue #170

---

src/lib/asce7-factory.js
src/lib/asce7_10-factory.js
src/lib/gridded-data-handler.js
src/lib/uht-hazard-curve-factory.js
src/lib/util/number-utils.js
test/uht-hazard-curve-factory.spec.js
test/util/number-utils.spec.js

Fix ASCE7-10 Factory order of operations

---

src/htdocs/asce41-13.html
src/htdocs/asce7-10.html

Updated markup for documentation.

---

package.json
src/lib/web-service.js

Fixes #196 
I also took the liberty to update the version in packages.json.

Fixed Bug #196.  Update product version to 0.5.0 in package.json

---

src/lib/asce41-handler.js
src/lib/asce41_13-handler.js
src/lib/asce41_17-handler.js
test/asce41-handler.spec.js
test/asce41_13-handler.spec.js
test/asce41_17-handler.spec.js

Refactor ASCE41Handlers and update tests

---

etc/asce7_05-qc.json

created asec7-05 QC json file

---

DISCLAIMER.md
src/htdocs/asce41-13.html
src/htdocs/asce41-17.html
src/htdocs/asce7-05.html
src/htdocs/asce7-10.html
src/htdocs/asce7-16.html
src/htdocs/deterministic.html
src/htdocs/index.html
src/htdocs/probabilistic.html
src/htdocs/risk-coefficient.html
src/htdocs/t-sub-l.html

Adding disclaimer to all html documentation.

Adding disclaimer to html

---

src/lib/docker-entrypoint.sh

Trying to get automated deployment to stage working.

Previous change is not working so reverting temporarily

---

src/htdocs/asce7-10.html
src/htdocs/ibc-2012.html
src/htdocs/ibc-2015.html
src/htdocs/nehrp-2009.html
src/lib/metadata-factory.js

fixing typo in output

---

src/lib/db/db-utils.js

Remove extra promise wrapper

---

src/lib/db/metadata/metadata.js
src/lib/db/probabilistic/documents.json
src/lib/db/probabilistic/regions.json

I think this commit should complete the data loader functionality for loading the AASHTO 2009 data.

Data loader changes for AASHTO 2009

---

Dockerfile
Jenkinsfile.groovy
package.json

- Increment version number
- Fix build with latest images

v0.7.1 rc1

---

src/htdocs/aashto-2009.html
src/htdocs/index.html

Here's a first-cut at the AASHTO docs.

AASHTO documentation

---

qc/expectations/aashto-2009.expectation.json
qc/expectations/aashto-2009.smoketest.json
qc/results/aashto-2009.qc.md
qc/smoketest.js
qc/update-quality-control.js

This branch includes the AASHTO-2009 smoketest and qc expectations.  All tests pass in my local environment.

AASHTO-2009 QC

---

src/htdocs/aashto-2009.html

The example request and response still need to be updated, when the service is finalized.

Additional updates to AASHTO-2009 documenation
